/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex("genres").del();
  await knex("genres").insert([
    { genre_id: 11, genre: "Dramas militares" },
    { genre_id: 26, genre: "Mockumentaries" },
    { genre_id: 83, genre: "TV Programmes" },
    { genre_id: 105, genre: "Mexican Comedies" },
    { genre_id: 180, genre: "Sports Documentaries" },
    { genre_id: 384, genre: "Independent Dramas" },
    { genre_id: 452, genre: "Anime Dramas" },
    { genre_id: 500, genre: "Gay & Lesbian Dramas" },
    { genre_id: 561, genre: "Films for ages 8 to 10" },
    { genre_id: 783, genre: "Children & Family Films" },
    { genre_id: 794, genre: "Steamy Dramas" },
    { genre_id: 798, genre: "Brazilian Films" },
    { genre_id: 799, genre: "Japanese Thrillers" },
    { genre_id: 869, genre: "Dark Comedies" },
    { genre_id: 875, genre: "Critically-acclaimed Independent Films" },
    { genre_id: 899, genre: "Critically-acclaimed Action & Adventure" },
    { genre_id: 920, genre: "Films Based on Real Life" },
    { genre_id: 947, genre: "Monster Films" },
    { genre_id: 1009, genre: "British Comedies" },
    { genre_id: 1096, genre: "Biographical Movies" },
    { genre_id: 1159, genre: "Travel & Adventure Documentaries" },
    { genre_id: 1252, genre: "Camp Films" },
    { genre_id: 1255, genre: "Dramas románticos" },
    { genre_id: 1302, genre: "British Action & Adventure" },
    { genre_id: 1365, genre: "Acción y aventuras" },
    { genre_id: 1372, genre: "Sci-Fi & Fantasy Programmes" },
    { genre_id: 1402, genre: "Late Night Comedies" },
    { genre_id: 1492, genre: "Sci-Fi & Fantasy" },
    { genre_id: 1568, genre: "Action Sci-Fi & Fantasy" },
    { genre_id: 1613, genre: "Latin American Films" },
    { genre_id: 1694, genre: "Sci-Fi Horror Films" },
    { genre_id: 1697, genre: "Czech Movies" },
    { genre_id: 1701, genre: "Music" },
    { genre_id: 1747, genre: "Japanese Comedies" },
    { genre_id: 1884, genre: "Scandinavian Crime Films" },
    { genre_id: 1989, genre: "Korean Drama Movies" },
    { genre_id: 2125, genre: "Acción y aventuras militares" },
    { genre_id: 2340, genre: "Teen Films" },
    { genre_id: 2477, genre: "Spy Films" },
    { genre_id: 2595, genre: "Science & Nature Docs" },
    { genre_id: 2653, genre: "Action Anime" },
    { genre_id: 2696, genre: "Scandinavian Dramas" },
    { genre_id: 2700, genre: "Political Comedies" },
    { genre_id: 2729, genre: "Anime Sci-Fi" },
    { genre_id: 2748, genre: "Courtroom Dramas" },
    { genre_id: 2893, genre: "Japanese Dramas" },
    { genre_id: 3063, genre: "Anime Feature Films" },
    { genre_id: 3179, genre: "Biographical Dramas" },
    { genre_id: 3215, genre: "Soccer Non-fiction" },
    { genre_id: 3269, genre: "Independent Thrillers" },
    { genre_id: 3278, genre: "Rock & Pop" },
    { genre_id: 3300, genre: "Italian Comedies" },
    { genre_id: 3327, genre: "Alien Sci-Fi" },
    { genre_id: 3329, genre: "Romantic Gay & Lesbian Films" },
    { genre_id: 3519, genre: "Comedias adolescentes" },
    { genre_id: 3652, genre: "Biographical Documentaries" },
    { genre_id: 3653, genre: "Dramas basados en la vida real" },
    { genre_id: 3675, genre: "Social & Cultural Docs" },
    { genre_id: 3682, genre: "British Dramas" },
    { genre_id: 3761, genre: "African Films" },
    { genre_id: 3830, genre: "Romantic Films based on a book" },
    { genre_id: 3903, genre: "Sitcoms" },
    { genre_id: 3916, genre: "Sci-Fi Dramas" },
    { genre_id: 3947, genre: "Social Issue Dramas" },
    { genre_id: 3960, genre: "Chinese Films" },
    { genre_id: 3979, genre: "Critically Acclaimed Films" },
    { genre_id: 3996, genre: "Latin American Comedies" },
    { genre_id: 4006, genre: "Military Documentaries" },
    { genre_id: 4058, genre: "Crime Comedies" },
    { genre_id: 4195, genre: "Independent Comedies" },
    { genre_id: 4282, genre: "Italian Dramas" },
    { genre_id: 4344, genre: "Japanese Action & Adventure" },
    { genre_id: 4366, genre: "Mystery Programmes" },
    { genre_id: 4370, genre: "Sports Films" },
    { genre_id: 4425, genre: "Brazilian Drama Movies" },
    { genre_id: 4698, genre: "Animation" },
    { genre_id: 4720, genre: "Gay & Lesbian Documentaries" },
    { genre_id: 4809, genre: "Psychological Horror Films" },
    { genre_id: 4922, genre: "Satires" },
    { genre_id: 4961, genre: "Dramas based on a book" },
    { genre_id: 5012, genre: "Showbiz Dramas" },
    { genre_id: 5230, genre: "Australian Films" },
    { genre_id: 5286, genre: "Sports Comedies" },
    { genre_id: 5349, genre: "Historical Documentaries" },
    { genre_id: 5455, genre: "Films for ages 5 to 7" },
    { genre_id: 5475, genre: "Comedias románticas" },
    { genre_id: 5480, genre: "Bollywood Films" },
    { genre_id: 5505, genre: "Psychological Thrillers" },
    { genre_id: 5507, genre: "Animal Tales" },
    { genre_id: 5685, genre: "Korean Films" },
    { genre_id: 5756, genre: "Raunchy Comedies" },
    { genre_id: 5763, genre: "Drama" },
    { genre_id: 5824, genre: "Crime Films" },
    { genre_id: 5875, genre: "Middle Eastern Movies" },
    { genre_id: 5962, genre: "Military Films" },
    { genre_id: 5977, genre: "Gay & Lesbian Films" },
    { genre_id: 6000, genre: "Japanese Sci-Fi & Fantasy" },
    { genre_id: 6047, genre: "Polish Thrillers" },
    { genre_id: 6073, genre: "Hip-Hop" },
    { genre_id: 6102, genre: "Polish Comedies" },
    { genre_id: 6133, genre: "Argentinian Films" },
    { genre_id: 6197, genre: "Goofy Comedies" },
    { genre_id: 6206, genre: "Critically Acclaimed Dramas" },
    { genre_id: 6218, genre: "Films for ages 2 to 4" },
    { genre_id: 6299, genre: "Polish Films" },
    { genre_id: 6384, genre: "Tearjerkers" },
    { genre_id: 6548, genre: "Comedias" },
    { genre_id: 6616, genre: "Dramas políticos" },
    { genre_id: 6626, genre: "Korean Comedies" },
    { genre_id: 6721, genre: "Anime Series" },
    { genre_id: 6763, genre: "Latin American Dramas" },
    { genre_id: 6814, genre: "Special Interest" },
    { genre_id: 6839, genre: "Documentaries" },
    { genre_id: 6889, genre: "Crime Dramas" },
    { genre_id: 6895, genre: "Creature Features" },
    { genre_id: 6926, genre: "Sci-Fi Adventure" },
    { genre_id: 6962, genre: "Films for ages 11 to 12" },
    { genre_id: 6998, genre: "Satanic Stories" },
    { genre_id: 7018, genre: "Political Documentaries" },
    { genre_id: 7077, genre: "Independent Films" },
    { genre_id: 7120, genre: "Gay & Lesbian Comedies" },
    { genre_id: 7243, genre: "Sports Drama Movies" },
    { genre_id: 7424, genre: "Anime" },
    { genre_id: 7442, genre: "Adventures" },
    { genre_id: 7539, genre: "TV Comedy Dramas" },
    { genre_id: 7627, genre: "Cult Films" },
    { genre_id: 7687, genre: "Film Noir" },
    { genre_id: 7700, genre: "Westerns" },
    { genre_id: 7825, genre: "Mexican Films" },
    { genre_id: 7908, genre: "Romantic Italian Films" },
    { genre_id: 7992, genre: "TV Animated Comedies" },
    { genre_id: 8221, genre: "Italian Films" },
    { genre_id: 8248, genre: "Korean Action & Adventure" },
    { genre_id: 8646, genre: "Slasher & Serial Killer Movies" },
    { genre_id: 8711, genre: "Horror Films" },
    { genre_id: 8883, genre: "Películas románticas" },
    { genre_id: 8933, genre: "Thriller Movies" },
    { genre_id: 8985, genre: "Martial Arts Films" },
    { genre_id: 8999, genre: "Chinese Action & Adventure" },
    { genre_id: 9147, genre: "Spy Thrillers" },
    { genre_id: 9196, genre: "Southeast Asian Movies" },
    { genre_id: 9229, genre: "Chinese Comedies" },
    { genre_id: 9292, genre: "Scandinavian Films" },
    { genre_id: 9299, genre: "Teen Dramas" },
    { genre_id: 9302, genre: "Anime Comedies" },
    { genre_id: 9327, genre: "Sports & Fitness" },
    { genre_id: 9434, genre: "Cult Comedies" },
    { genre_id: 9509, genre: "Gory Horror Films" },
    { genre_id: 9584, genre: "Crime Action & Adventure" },
    { genre_id: 9736, genre: "Critically Acclaimed Comedies" },
    { genre_id: 9744, genre: "Fantasy" },
    { genre_id: 9833, genre: "Reality Programmes" },
    { genre_id: 9873, genre: "Dutch Dramas" },
    { genre_id: 9875, genre: "Crime Documentaries" },
    { genre_id: 9889, genre: "Films Based on Books" },
    { genre_id: 9916, genre: "Romantic Independent Films" },
    { genre_id: 9994, genre: "Mysteries" },
    { genre_id: 10056, genre: "Films based on childrens books" },
    { genre_id: 10105, genre: "Documentary Programmes" },
    { genre_id: 10118, genre: "Comic Book and Superhero Films" },
    { genre_id: 10256, genre: "Slapstick Comedies" },
    { genre_id: 10375, genre: "Comedy Programmes" },
    { genre_id: 10398, genre: "Japanese Films" },
    { genre_id: 10455, genre: "Romantic British Films" },
    { genre_id: 10463, genre: "Indian Films" },
    { genre_id: 10499, genre: "Crime Thriller Movies" },
    { genre_id: 10504, genre: "Political Thrillers" },
    { genre_id: 10606, genre: "Dutch Films" },
    { genre_id: 10634, genre: "TV Soaps" },
    { genre_id: 10659, genre: "Education & Guidance" },
    { genre_id: 10673, genre: "Action & Adventure Programmes" },
    { genre_id: 10695, genre: "Anime Horror Films" },
    { genre_id: 10702, genre: "Spy Action & Adventure" },
    { genre_id: 10714, genre: "Courtroom Films" },
    { genre_id: 10741, genre: "Latin Music" },
    { genre_id: 10757, genre: "British Films" },
    { genre_id: 10832, genre: "Theater Arts" },
    { genre_id: 10869, genre: "Filipino Films" },
    { genre_id: 10944, genre: "Cult Horror Films" },
    { genre_id: 11014, genre: "Sci-Fi Thrillers" },
    { genre_id: 11039, genre: "Irreverent Stand-up Comedy" },
    { genre_id: 11140, genre: "Supernatural Thrillers" },
    { genre_id: 11146, genre: "Anime Fantasies" },
    { genre_id: 11177, genre: "Tegnefilmserier" },
    { genre_id: 11283, genre: "Korean Thrillers" },
    { genre_id: 11559, genre: "Stand-up Comedy" },
    { genre_id: 11567, genre: "Russian" },
    { genre_id: 11714, genre: "Drama Programmes" },
    { genre_id: 11729, genre: "Polish Dramas" },
    { genre_id: 11755, genre: "Scandinavian Comedies" },
    { genre_id: 11804, genre: "Independent Action & Adventure" },
    { genre_id: 11881, genre: "Adult Animation" },
    { genre_id: 12123, genre: "Ambientadas en otra época" },
    { genre_id: 12739, genre: "20th Century Period Pieces" },
    { genre_id: 12803, genre: "Football Films" },
    { genre_id: 12994, genre: "Dramas based on contemporary literature" },
    { genre_id: 13158, genre: "Dramas based on classic literature" },
    { genre_id: 13335, genre: "Musicals" },
    { genre_id: 16890, genre: "Romantic Korean Movies" },
    { genre_id: 17648, genre: "Brazilian Comedies" },
    { genre_id: 25801, genre: "Courtroom TV Programmes" },
    { genre_id: 25807, genre: "Political TV Programmes" },
    { genre_id: 26009, genre: "Crime TV Dramas" },
    { genre_id: 26049, genre: "Romantic TV Comedies" },
    { genre_id: 26056, genre: "Romantic TV Dramas" },
    { genre_id: 26146, genre: "Crime Programmes" },
    { genre_id: 26156, genre: "Romance Programmes" },
    { genre_id: 26835, genre: "Faith & Spirituality" },
    { genre_id: 27018, genre: "Heist Films" },
    { genre_id: 27346, genre: "Barne-TV" },
    { genre_id: 27756, genre: "Heist Action & Adventure" },
    { genre_id: 28034, genre: "Kids TV for ages 5 to 7" },
    { genre_id: 28083, genre: "Kids TV for ages 8 to 10" },
    { genre_id: 28134, genre: "Buddy Comedies" },
    { genre_id: 28269, genre: "Brazilian Documentaries" },
    { genre_id: 29281, genre: "Steamy Romance" },
    { genre_id: 29809, genre: "Classic Dramas" },
    { genre_id: 30140, genre: "Gangster Action & Adventure" },
    { genre_id: 31574, genre: "Classic Films" },
    { genre_id: 31694, genre: "Classic Comedies" },
    { genre_id: 31851, genre: "Gangster Films" },
    { genre_id: 31901, genre: "Family Dramas" },
    { genre_id: 34028, genre: "Medical TV Programmes" },
    { genre_id: 35800, genre: "Steamy Romantic Films" },
    { genre_id: 36103, genre: "Quirky Romance" },
    { genre_id: 42023, genre: "Supernatural Horror Films" },
    { genre_id: 43040, genre: "Action Comedies" },
    { genre_id: 43048, genre: "Action Thrillers" },
    { genre_id: 46576, genre: "Classic Action & Adventure" },
    { genre_id: 48768, genre: "Nature & Ecology Documentaries" },
    { genre_id: 49266, genre: "Competition Reality TV" },
    { genre_id: 49296, genre: "Makeover Reality TV" },
    { genre_id: 50103, genre: "Wedding & Romance Reality TV" },
    { genre_id: 51056, genre: "Family Features" },
    { genre_id: 51058, genre: "Family Feature Animation" },
    { genre_id: 51063, genre: "Academy Award-Winning Films" },
    { genre_id: 52117, genre: "British Programmes" },
    { genre_id: 52140, genre: "British TV Comedies" },
    { genre_id: 52147, genre: "Teen Screams" },
    { genre_id: 52148, genre: "British TV Dramas" },
    { genre_id: 52387, genre: "Australian TV Programmes" },
    { genre_id: 52780, genre: "Science & Nature TV" },
    { genre_id: 52804, genre: "Faith & Spirituality Films" },
    { genre_id: 52843, genre: "Kids Music" },
    { genre_id: 52847, genre: "Family Comedies" },
    { genre_id: 52849, genre: "Family Sci-Fi & Fantasy" },
    { genre_id: 52852, genre: "Music & Musicals" },
    { genre_id: 52855, genre: "Family Adventure Movies" },
    { genre_id: 52858, genre: "Epics" },
    { genre_id: 53717, genre: "Comic Book & Superhero TV" },
    { genre_id: 53915, genre: "Teen Romance" },
    { genre_id: 56181, genre: "Canadian Films" },
    { genre_id: 58676, genre: "Hong Kong Films" },
    { genre_id: 58700, genre: "Danish Films" },
    { genre_id: 58704, genre: "Canadian TV Programmes" },
    { genre_id: 58741, genre: "Spanish Films" },
    { genre_id: 58755, genre: "German Dramas" },
    { genre_id: 58796, genre: "Spanish Dramas" },
    { genre_id: 58806, genre: "Hindi-language Films" },
    { genre_id: 58807, genre: "Franse films" },
    { genre_id: 58879, genre: "Family Animation" },
    { genre_id: 58886, genre: "German Films" },
    { genre_id: 58905, genre: "French Comedies" },
    { genre_id: 59849, genre: "Malayalam-language Films" },
    { genre_id: 59872, genre: "Indian Programmes" },
    { genre_id: 60724, genre: "Thai Comedies" },
    { genre_id: 60951, genre: "Teen Programmes" },
    { genre_id: 61091, genre: "Teen TV Dramas" },
    { genre_id: 61205, genre: "Thai Films" },
    { genre_id: 61330, genre: "Spanish Comedies" },
    { genre_id: 61695, genre: "German Crime Movies" },
    { genre_id: 61904, genre: "Tamil-language Films" },
    { genre_id: 62016, genre: "Swedish Films" },
    { genre_id: 62041, genre: "French TV Programmes" },
    { genre_id: 62116, genre: "Thai Drama Movies" },
    { genre_id: 62510, genre: "Norwegian Films" },
    { genre_id: 62866, genre: "Italian TV Programmes" },
    { genre_id: 63092, genre: "Swedish Comedies" },
    { genre_id: 63115, genre: "German Comedies" },
    { genre_id: 63315, genre: "Thai Action & Adventure" },
    { genre_id: 63676, genre: "Telugu-Language Films" },
    { genre_id: 64256, genre: "Japanese Programmes" },
    { genre_id: 65198, genre: "German TV Programmes" },
    { genre_id: 65209, genre: "Thai Horror Films" },
    { genre_id: 65263, genre: "LGBTQ TV Programmes" },
    { genre_id: 65925, genre: "Japanese Kids TV" },
    { genre_id: 67644, genre: "Mexican TV Programmes" },
    { genre_id: 67708, genre: "Latin American TV Programmes" },
    { genre_id: 67879, genre: "Korean Programmes" },
    { genre_id: 69192, genre: "Scandinavian Independent Movies" },
    { genre_id: 69616, genre: "Argentinian TV Shows" },
    { genre_id: 69622, genre: "Colombian TV Programmes" },
    { genre_id: 69624, genre: "Brazilian TV Programmes" },
    { genre_id: 69636, genre: "Colombian Movies" },
    { genre_id: 69946, genre: "BAFTA Award-Winning Films" },
    { genre_id: 71590, genre: "Historical Films" },
    { genre_id: 71591, genre: "Historical Drama Movies" },
    { genre_id: 72404, genre: "American Programmes" },
    { genre_id: 72436, genre: "Food & Travel TV" },
    { genre_id: 75390, genre: "Police Thriller Movies" },
    { genre_id: 75392, genre: "Police TV Shows" },
    { genre_id: 75405, genre: "Zombie Horror Films" },
    { genre_id: 75415, genre: "Police Mysteries" },
    { genre_id: 75418, genre: "Police Action & Adventure" },
    { genre_id: 75436, genre: "Police Movies" },
    { genre_id: 75459, genre: "Police Dramas" },
    { genre_id: 76186, genre: "Modern Classic Movies" },
    { genre_id: 76793, genre: "Swedish TV Programmes" },
    { genre_id: 76802, genre: "Scandinavian TV" },
    { genre_id: 77230, genre: "Politically Incorrect Stand-up Comedy" },
    { genre_id: 77232, genre: "Asian Action Films" },
    { genre_id: 78103, genre: "Asian Programmes" },
    { genre_id: 78104, genre: "Asian Movies" },
    { genre_id: 78141, genre: "Nordic Movies" },
    { genre_id: 78367, genre: "Internationaal" },
    { genre_id: 78628, genre: "Nordic Dramas" },
    { genre_id: 78634, genre: "Nordic TV Shows" },
    { genre_id: 78655, genre: "Nordic Comedies" },
    { genre_id: 79049, genre: "Police Detective Movies" },
    { genre_id: 79871, genre: "Dutch Comedies" },
    { genre_id: 80307, genre: "Hindi-language TV Programmes" },
    { genre_id: 80353, genre: "Chinese  Programmes" },
    { genre_id: 81050, genre: "True Crime Documentaries" },
    { genre_id: 82489, genre: "Golden Globe Award-winning Films" },
    { genre_id: 83059, genre: "Horror Programmes" },
    { genre_id: 84483, genre: "Music and Concert Films" },
    { genre_id: 84488, genre: "Brazilian Music & Musicals" },
    { genre_id: 89442, genre: "Dutch TV Shows" },
    { genre_id: 89513, genre: "Dutch Children & Family Movies" },
    { genre_id: 89585, genre: "Horror Comedies" },
    { genre_id: 89663, genre: "European TV Shows" },
    { genre_id: 89680, genre: "European Dramas" },
    { genre_id: 89682, genre: "European Comedies" },
    { genre_id: 89708, genre: "European Movies" },
    { genre_id: 89712, genre: "Romantic European Movies" },
    { genre_id: 89804, genre: "Award Winning Drama Films" },
    { genre_id: 89811, genre: "Thriller Programmes" },
    { genre_id: 89844, genre: "Award-films" },
    { genre_id: 90166, genre: "Blockbuster Sci-Fi & Fantasy" },
    { genre_id: 90176, genre: "Blockbuster Action & Adventure" },
    { genre_id: 90361, genre: "Music & Concert Documentaries" },
    { genre_id: 90848, genre: "Chilling Horror Films" },
    { genre_id: 108533, genre: "Sci-Fi" },
    { genre_id: 413820, genre: "Kids Anime" },
    { genre_id: 502675, genre: "Romantic Favorites" },
    { genre_id: 667429, genre: "Taiwanese TV Programmes" },
    { genre_id: 711366, genre: "Japanese TV Comedies" },
    { genre_id: 711367, genre: "Japanese TV Dramas" },
    { genre_id: 786708, genre: "Animated Movies" },
    { genre_id: 788212, genre: "Crime Action" },
    { genre_id: 801362, genre: "Action" },
    { genre_id: 846216, genre: "Films Based on a Play" },
    { genre_id: 852488, genre: "International Thrillers" },
    { genre_id: 852490, genre: "International Action & Adventure" },
    { genre_id: 852491, genre: "International Sci-Fi & Fantasy" },
    { genre_id: 852492, genre: "International Comedies" },
    { genre_id: 852493, genre: "International Dramas" },
    { genre_id: 852494, genre: "International Documentaries" },
    { genre_id: 1002031, genre: "Fantasy TV Programmes" },
    { genre_id: 1003219, genre: "Comedy Blockbusters" },
    { genre_id: 1023212, genre: "Home & Garden Reality TV" },
    { genre_id: 1133133, genre: "Turkish Films" },
    { genre_id: 1133134, genre: "Turkish Comedies" },
    { genre_id: 1138254, genre: "Nollywood Films" },
    { genre_id: 1138506, genre: "Japanese TV Thrillers" },
    { genre_id: 1159493, genre: "US Movies" },
    { genre_id: 1159504, genre: "South African Films" },
    { genre_id: 1193084, genre: "Spanish TV Programmes" },
    { genre_id: 1195213, genre: "International Programmes" },
    { genre_id: 1208954, genre: "International TV Dramas" },
    { genre_id: 1295410, genre: "Romantic International TV Shows" },
    { genre_id: 1333288, genre: "Laugh-Out-Loud Comedies" },
    { genre_id: 1408777, genre: "Retro Anime" },
    { genre_id: 1433679, genre: "Anime Sci-Fi & Fantasy" },
    { genre_id: 1461905, genre: "Taiwanese Movies" },
    { genre_id: 1474327, genre: "Romantic International Movies" },
    { genre_id: 1476847, genre: "Middle Eastern TV Programmes" },
    { genre_id: 1502288, genre: "Youth Drama" },
    { genre_id: 1516534, genre: "Stand-up & Chat Shows" },
    { genre_id: 1519160, genre: "Japanese Movies based on Comics" },
    { genre_id: 1519826, genre: "Slice of Life Anime" },
    { genre_id: 1522234, genre: "Romance Anime" },
    { genre_id: 1522235, genre: "Cyborg & Robot Anime" },
    { genre_id: 1622170, genre: "Polish TV Programmes" },
    { genre_id: 1622375, genre: "Sports Anime" },
    { genre_id: 1623841, genre: "School Anime" },
    { genre_id: 1626246, genre: "Futuristic Sci-Fi" },
    { genre_id: 1652485, genre: "Japanese Youth Dramas" },
    { genre_id: 1655810, genre: "Romantic Youth Drama" },
    { genre_id: 1819174, genre: "TV Programmes Based on Books" },
    { genre_id: 1819198, genre: "TV Dramas based on Comics" },
    { genre_id: 1819776, genre: "Anime based on Books" },
    { genre_id: 1819777, genre: "Anime based on a Video Game" },
    { genre_id: 1827694, genre: "Owarai & Variety Shows" },
    { genre_id: 1964512, genre: "Cyberpunk" },
    { genre_id: 2070375, genre: "International Reality, Talk & Variety Shows" },
    { genre_id: 2070390, genre: "Reality, Variety & Talk Shows" },
    { genre_id: 2070675, genre: "Variety Entertainment" },
    { genre_id: 2072262, genre: "Family Watch Together TV" },
    { genre_id: 2072269, genre: "Korean Reality, Variety & Talk Shows" },
    { genre_id: 2075446, genre: "Historical Anime" },
    { genre_id: 2190064, genre: "Marathi-Language Movies" },
    { genre_id: 2192320, genre: "TV Shows based on Comics" },
    { genre_id: 2192322, genre: "TV Shows Based on Real Life" },
    { genre_id: 2199520, genre: "Mainland Chinese Movies" },
    { genre_id: 2199564, genre: "Mainland Chinese TV Shows" },
    { genre_id: 2243108, genre: "Documentaries" },
    { genre_id: 2245805, genre: "Family Cozy Time" },
    { genre_id: 2300054, genre: "Blue Dragon Film Award-winning Movies" },
    { genre_id: 2300348, genre: "Baeksang Arts Awards Winners" },
    { genre_id: 2316199, genre: "Anime based on Comics" },
    { genre_id: 2638104, genre: "K-dramas" },
    { genre_id: 2691116, genre: "Social Issue TV Dramas" },
    { genre_id: 2691923, genre: "Japanese TV Series" },
    { genre_id: 2691981, genre: "Youth TV Dramas" },
    { genre_id: 2699150, genre: "Thai TV Programmes" },
    { genre_id: 2738568, genre: "Lifestyle" },
    { genre_id: 2867320, genre: "Indonesian Films" },
    { genre_id: 2867325, genre: "Anime Based on Light Novels" },
    { genre_id: 2867624, genre: "Shounen Anime" },
    { genre_id: 2913945, genre: "Seinen Anime" },
    { genre_id: 2936382, genre: "K-dramas based on Webtoon" },
    { genre_id: 2951909, genre: "TV Programmes Based on Manga" },
    { genre_id: 3030851, genre: "Talk Shows" },
    { genre_id: 3057773, genre: "Malaysian Films" },
    { genre_id: 3276033, genre: "Sci-Fi Films" },
    { genre_id: 3300242, genre: "Sci-Fi TV" },
    { genre_id: 81216565, genre: "Mystery & Thriller Anime" },
    { genre_id: 81216629, genre: "Romantic Comedy Anime" },
    { genre_id: 81248636, genre: "Concerts" },
    { genre_id: 81306797, genre: "Singaporean Movies" },
    { genre_id: 81329745, genre: "Variety TV" },
    { genre_id: 81399454, genre: "French" },
    { genre_id: 81399656, genre: "British" },
    { genre_id: 81399657, genre: "Spanish" },
    { genre_id: 81404209, genre: "Nollywood" },
    { genre_id: 81417788, genre: "Argentinian" },
    { genre_id: 81417793, genre: "Brazilian" },
    { genre_id: 81417795, genre: "German" },
    { genre_id: 81417798, genre: "Italian" },
    { genre_id: 81417800, genre: "Mexican" },
    { genre_id: 81417804, genre: "Taiwanese" },
    { genre_id: 81417808, genre: "Turkish" },
    { genre_id: 81418152, genre: "Canadian" },
    { genre_id: 81418153, genre: "Colombian" },
    { genre_id: 81418154, genre: "Swedish" },
    { genre_id: 81418679, genre: "Danish" },
    { genre_id: 81418681, genre: "Finnish" },
    { genre_id: 81418683, genre: "Indian" },
    { genre_id: 81418687, genre: "Japanese" },
    { genre_id: 81422104, genre: "Dutch" },
    { genre_id: 81422105, genre: "Norwegian" },
    { genre_id: 81422106, genre: "Filipino" },
    { genre_id: 81422107, genre: "Polish" },
    { genre_id: 81422108, genre: "Singaporean" },
    { genre_id: 81422109, genre: "Thai" },
    { genre_id: 81427741, genre: "Australian" },
    { genre_id: 81427742, genre: "Austrian" },
    { genre_id: 81427743, genre: "Belgian" },
    { genre_id: 81427748, genre: "Bulgarian" },
    { genre_id: 81427750, genre: "Chilean" },
    { genre_id: 81427753, genre: "Hong Kong" },
    { genre_id: 81427754, genre: "Irish" },
    { genre_id: 81427755, genre: "Israeli" },
    { genre_id: 81427756, genre: "Korean" },
    { genre_id: 81427762, genre: "Portuguese" },
    { genre_id: 81427764, genre: "Swiss" },
    { genre_id: 81444566, genre: "Czech" },
    { genre_id: 81444569, genre: "Egyptian" },
    { genre_id: 81444570, genre: "Greek" },
    { genre_id: 81444581, genre: "South African" },
    { genre_id: 81444582, genre: "Ukrainian" },
    { genre_id: 81444584, genre: "Vietnamese" },
    { genre_id: 81448926, genre: "Hungarian" },
    { genre_id: 81448928, genre: "Romanian" },
    { genre_id: 81458611, genre: "Indonesian" },
    { genre_id: 81458620, genre: "Saudi" },
    { genre_id: 81458622, genre: "Kuwaiti" },
    { genre_id: 81458633, genre: "Lebanese" },
    { genre_id: 81458634, genre: "Malaysian" },
    { genre_id: 81458642, genre: "Emirati" },
    { genre_id: 81562604, genre: "Docuseries" },
    { genre_id: 81562614, genre: "Social & Cultural Docs" },
    { genre_id: 81711249, genre: "Kids Movies" },
  ]);
};
